baseURL = "http://example.com/"
languageCode = "en-us"
title = "Joseph L. Sanders"
theme = "hugo-coder"
defaultcontentlanguage = "en"

[params]
    author = "Joseph Sanders"
    info = "Errata Ad Nauseam"
    avatarurl = "https://avatars0.githubusercontent.com/u/13022493?s=460&v=4"

    inverted = true

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[params.social]]
    url = "mailto:contact@sandco.io"
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 1

[[params.social]]
    url = "https://github.com/jls83/"
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2

[[params.social]]
    url = "https://www.linkedin.com/in/josephlsanders/"
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3

[[params.social]]
    url = "https://stackoverflow.com/users/5209981/jls83"
    name = "Stack Overflow"
    icon = "fab fa-stack-overflow fa-2x"
    weight = 4
